// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Category struct {
	ID       int64         `json:"id"`
	Name     string        `json:"name"`
	ParentID sql.NullInt64 `json:"parent_id"`
}

type Customer struct {
	ID        int64         `json:"id"`
	Name      string        `json:"name"`
	Email     string        `json:"email"`
	Phone     sql.NullInt64 `json:"phone"`
	OidcSub   string        `json:"oidc_sub"`
	CreatedAt time.Time     `json:"created_at"`
}

type Order struct {
	ID         int64     `json:"id"`
	CustomerID int64     `json:"customer_id"`
	CreatedAt  time.Time `json:"created_at"`
	Total      string    `json:"total"`
}

type OrderItem struct {
	ID        int64  `json:"id"`
	OrderID   int64  `json:"order_id"`
	ProductID int64  `json:"product_id"`
	Quantity  int32  `json:"quantity"`
	Subtotal  string `json:"subtotal"`
}

type Product struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	CreatedAt   time.Time      `json:"created_at"`
}

type ProductCategory struct {
	ProductID  int64 `json:"product_id"`
	CategoryID int64 `json:"category_id"`
}
