# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_DB: order
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: root
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U root" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.x'

    - name: Install migrate
      run: |
        version=4.15.2
        os=$(uname | tr '[:upper:]' '[:lower:]')
        arch=$(uname -m)
        if [ "$arch" = "x86_64" ]; then arch="amd64"; fi
        if [ "$arch" = "aarch64" ]; then arch="arm64"; fi
        curl -L https://github.com/golang-migrate/migrate/releases/download/v${version}/migrate.${os}-${arch}.tar.gz \
        | tar -xz
        sudo mv migrate /usr/local/bin/migrate
        migrate -version

    - name: Run migrations
      run: migrate -path db/migration -database "postgresql://root:secret@localhost:5432/order?sslmode=disable" -verbose up
    - name: Test
      run: go test -v ./...
